StockCharcha/Controllers/SiteActivityController.cs
using StockCharcha.DataAccess;
using StockCharcha.Filters;
using StockCharcha.Helpers;
using StockCharcha.Models;
using StockCharcha.Utils;
using StockCharcha.Utils.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StockCharcha.Controllers
{
    public class SiteActivityController : Controller
    {
        private StockCharchaEntities db = new StockCharchaEntities();
        public const int PageSize = CommonConstants.PageSize;
        [SessionExistFilter]
        public ActionResult Index()
        {
            List<SiteActivityModel> siteActivityList = new List<SiteActivityModel>();
            var siteActivity = new PagedData<SiteActivityModel>();
            try
            {
                var siteActivities = db.SiteActivities.OrderByDescending(x => x.ModifiedON).ToList();

                siteActivityList.AddRange(siteActivities.Select(x => new SiteActivityModel
                {
                    SiteActivityID = x.SiteActivityID,
                    ModuleName = x.ModuleName,
                    WebURL = x.WebURL,
                    ModifiedName = x.ModifiedBY != Guid.Empty && x.ModifiedBY != null ? Membership.GetUser((Guid)x.ModifiedBY).UserName.ToString() : string.Empty,
                    ModifiedONDate = String.Format("{0:dd/MM/yyyy}", x.ModifiedON)
                }));
                siteActivity.Data = siteActivityList.Take(PageSize).OrderByDescending(x => x.ModifiedON).ToList();
                siteActivity.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)siteActivityList.Count() / PageSize));
                siteActivity.CurrentPage = 1;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(siteActivity);
        }

        public ActionResult GetListByPage(string searchText, int page)
        {
            List<SiteActivityModel> siteActivityList = new List<SiteActivityModel>();
            var siteActivity = new PagedData<SiteActivityModel>();
            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    siteActivity = GetList(searchText, page);
                    return PartialView("_SiteActivityList", siteActivity);
                }

                var siteActivities = db.SiteActivities.OrderByDescending(x => x.ModifiedON).ToList();

                siteActivityList.AddRange(siteActivities.Select(x => new SiteActivityModel
                {
                    SiteActivityID = x.SiteActivityID,
                    ModuleName = x.ModuleName,
                    WebURL = x.WebURL,
                    ModifiedName = x.ModifiedBY != Guid.Empty && x.ModifiedBY != null ? Membership.GetUser((Guid)x.ModifiedBY).UserName.ToString() : string.Empty,
                    ModifiedONDate = String.Format("{0:dd/MM/yyyy}", x.ModifiedON)
                }));
                siteActivity.Data = siteActivityList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.ModifiedON).ToList();
                siteActivity.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)siteActivityList.Count() / PageSize));
                siteActivity.CurrentPage = page;
                return PartialView("_SiteActivityList", siteActivity);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return PartialView("_SiteActivityList", new PagedData<Blog>());
        }

        //[HttpGet]
        public PagedData<SiteActivityModel> GetList(string searchText, int page)
        {
            List<SiteActivityModel> siteActivityList = new List<SiteActivityModel>();
            var siteActivity = new PagedData<SiteActivityModel>();
            try
            {
                var siteActivities = db.SiteActivities.Where(x => x.ModuleName.ToLower().Contains(searchText) || x.WebURL.ToLower().Contains(searchText)).OrderByDescending(x => x.ModifiedON).ToList();

                siteActivityList.AddRange(siteActivities.Select(x => new SiteActivityModel
                {
                    SiteActivityID = x.SiteActivityID,
                    ModuleName = x.ModuleName,
                    WebURL = x.WebURL,
                    ModifiedName = x.ModifiedBY != Guid.Empty && x.ModifiedBY != null ? Membership.GetUser((Guid)x.ModifiedBY).UserName.ToString() : string.Empty,
                    ModifiedONDate = String.Format("{0:dd/MM/yyyy}", x.ModifiedON)
                }));
                siteActivity.Data = siteActivityList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.ModifiedON).ToList();
                siteActivity.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)siteActivityList.Count() / PageSize));
                siteActivity.CurrentPage = page;
                return siteActivity;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return new PagedData<SiteActivityModel>();
        }
    }
}

StockCharcha/Views/SiteActivity/Index.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.SiteActivityModel>
@using StockCharcha.Utils

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/admin/css/adminLoading.css" rel="stylesheet" />
<script src="@Url.Content("~/Content/admin/scripts/jquery-1.8.2.min.js")"></script>
@*<script src="~/Scripts/bootstrap.min.js"></script>*@

<script type="text/javascript">
    $(window).load(function () {
        // Animate loader off screen
        $(".adminLoading").fadeOut("slow");;
    });
    $(document).ready(function () {
        $("#btnSearch").click(function (evt) {
            $(".adminLoading").fadeIn("slow")
            $.get('@Url.Action("GetListByPage")', { "searchText": $("#searchText").val(), "page": 1 },
                    function (data) {
                        $("#searchList").html(data);
                        $(".adminLoading").fadeOut("slow");
                    });
        });
    });
</script>

<div class="notifications-align">
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInsertStatus)
    {
        <div class="alert alert-success show top-notification">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelUpdateStatus)
    {
        <div class="alert alert-success show top-notification">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInvalidStatus)
    {
        <div class="alert alert-danger show top-notification" style="padding: 8px;">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Site Activity</h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "SiteActivity")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Index</li>
    </ol>
</section>

<!-- Main content -->
<div class="adminLoading"></div>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title"><a style="display:none;" href="@Url.Action("Create", "SiteActivity")" class="btn btn-block btn-primary">Add New</a></h3>
            <div class="box-tools" style="top: 10px;">
                <div class="input-group" style="width: 250px;">
                    <input type="text" name="table_search" id="searchText" class="form-control input-sm pull-right" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-sm btn-default" id="btnSearch"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div><!-- /.box-header -->
        <div id="searchList">
            @Html.Partial("_SiteActivityList")
        </div>

    </div><!-- /.box -->
</section><!-- /.content -->

StockCharcha/Views/SiteActivity/_SiteActivityList.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.SiteActivityModel>
@using StockCharcha.Utils

<script src="~/Content/admin/bootstrap/js/jquery.bootpag.js"></script>
<script src="~/Content/admin/scripts/Shared/Common.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        Common.Paging(@Model.NumberOfPages, @Model.CurrentPage, "SiteActivity");
    });
</script>

<div class="box-body table-responsive no-padding">
    @if (Model.Data.Count() == 0 || Model == null)
    {
        int cnt = Model.Data.Count() + 1;
        <table class="table table-striped">
            <tr>
                <td colspan="@cnt">No Records Found.</td>
            </tr>
        </table>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Module Name</th>
                    <th>Web URL</th>
                    <th>Modified Name</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody id="itemContainer">
                @foreach (var item in Model.Data.OrderByDescending(x => x.ModifiedON))
                {
                    <tr>
                        <td>@item.ModuleName</td>
                        <td>@item.WebURL</td>
                        <td>@item.ModifiedName</td>
                        <td>@item.ModifiedONDate</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <p class="paging"></p>
                    </td>
                </tr>
            </tfoot>
        </table>
    }

</div><!-- /.box-body -->