StockCharcha/Controllers/ReportUsersController.cs
using StockCharcha.DataAccess;
using StockCharcha.Filters;
using StockCharcha.Helpers;
using StockCharcha.Models;
using StockCharcha.Utils;
using StockCharcha.Utils.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace StockCharcha.Controllers
{
    public class ReportUsersController : Controller
    {
        private StockCharchaEntities db = new StockCharchaEntities();
        public const int PageSize = CommonConstants.PageSize;

        [SessionExistFilter]
        public ActionResult Index()
        {
            List<ReportUserModel> reportUserModelList = new List<ReportUserModel>();
            var reportUserModel = new PagedData<ReportUserModel>();
            try
            {
                var reportUserList = db.ReportUsers.OrderByDescending(x => x.CreatedOn).ToList();

                reportUserModelList.AddRange(reportUserList.Select(x => new ReportUserModel
                {
                    Id = x.Id,
                    FromUser = Membership.GetUser(x.FromUser).UserName,
                    ToUser = Membership.GetUser(x.ToUser).UserName,
                    Comments = x.Comments,
                    CreatedOn = x.CreatedOn,
                    IsActive = x.IsActive
                }));

                reportUserModel.Data = reportUserModelList.Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                reportUserModel.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)reportUserModelList.Count() / PageSize));
                reportUserModel.CurrentPage = 1;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(reportUserModel);
        }

        public PagedData<ReportUserModel> GetList(string searchText, int page)
        {
            try
            {
                List<ReportUserModel> reportUserModelList = new List<ReportUserModel>();
                var reportUser = new PagedData<ReportUserModel>();

                var reportUserList = db.ReportUsers.OrderByDescending(x => x.CreatedOn).ToList();
                reportUserModelList.AddRange(reportUserList.Select(x => new ReportUserModel
                {
                    Id = x.Id,
                    FromUser = Membership.GetUser(x.FromUser).UserName,
                    ToUser = Membership.GetUser(x.ToUser).UserName,
                    Comments = x.Comments,
                    CreatedOn = x.CreatedOn,
                    IsActive = x.IsActive
                }));

                var reportUsersSearchList = reportUserModelList.Where(x => x.ToUser.ToLower().Contains(searchText) || x.FromUser.ToLower().Contains(searchText)).ToList();

                reportUser.Data = reportUsersSearchList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                reportUser.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)reportUsersSearchList.Count() / PageSize));
                reportUser.CurrentPage = page;
                return reportUser;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return new PagedData<ReportUserModel>();
        }

        public ActionResult GetListByPage(string searchText, int page)
        {
            List<ReportUserModel> reportUserModelList = new List<ReportUserModel>();
            var reportUserModel = new PagedData<ReportUserModel>();
            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    reportUserModel = GetList(searchText, page);
                    return PartialView("_ReportUserList", reportUserModel);
                }

                var reportUserList = db.ReportUsers.OrderByDescending(x => x.CreatedOn).ToList();
                reportUserModelList.AddRange(reportUserList.Select(x => new ReportUserModel
                {
                    Id = x.Id,
                    FromUser = Membership.GetUser(x.FromUser).UserName,
                    ToUser = Membership.GetUser(x.ToUser).UserName,
                    Comments = x.Comments,
                    CreatedOn = x.CreatedOn,
                    IsActive = x.IsActive
                }));

                reportUserModel.Data = reportUserModelList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                reportUserModel.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)reportUserModelList.Count() / PageSize));
                reportUserModel.CurrentPage = page;
                return PartialView("_ReportUserList", reportUserModel);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return PartialView("_ReportUserList", new PagedData<ReportUserModel>());
        }

        public JsonResult updateIsActive(long reportUserId, int isActive)
        {
            try
            {
                ReportUser reportUser = db.ReportUsers.Find(reportUserId);
                if (isActive == 0)
                {
                    reportUser.IsActive = false;
                    db.SaveChanges();

                    //Lock User from login.
                    MembershipUser mu = Membership.GetUser(reportUser.ToUser);
                    mu.IsApproved = false;
                    Membership.UpdateUser(mu);

                    SiteActivityErrorsUtil.SiteActivity("updateIsActive", "", "Report User locked");
                    return Json("User Locked.");
                }
                else
                {
                    reportUser.IsActive = true;
                    db.SaveChanges();

                    //Lock User from login.
                    MembershipUser mu = Membership.GetUser(reportUser.ToUser);
                    mu.IsApproved = true;
                    Membership.UpdateUser(mu);

                    SiteActivityErrorsUtil.SiteActivity("updateIsActive", "", "Report User Unlocked");
                    return Json("User UnLocked.");
                }
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return Json("Something went wrong.");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockCharcha/Views/ReportUsers/Index.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.ReportUserModel>
@using StockCharcha.Utils

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/admin/css/adminLoading.css" rel="stylesheet" />
<script src="@Url.Content("~/Content/admin/scripts/jquery-1.8.2.min.js")"></script>

<script type="text/javascript">
    $(window).load(function () {
        // Animate loader off screen
        $(".adminLoading").fadeOut("slow");
    });
    $(document).ready(function () {
        $("#btnSearch").click(function (evt) {
            $(".adminLoading").fadeIn("slow")
            $.get('@Url.Action("GetListByPage")', { "searchText": $("#searchText").val(), "page": 1 },
                    function (data) {
                        $("#searchList").html(data);
                        $(".adminLoading").fadeOut("slow");
                    });
        });

    });
</script>

<div class="notifications-align">
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInsertStatus)
    {
        <div class="alert alert-success show top-notification">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelUpdateStatus)
    {
        <div class="alert alert-success show top-notification">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInvalidStatus)
    {
        <div class="alert alert-danger show top-notification" style="padding: 8px;">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Report User</h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "ReportUsers")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Index</li>
    </ol>
</section>

<!-- Main content -->
<div class="adminLoading"></div>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title"><a style="display:none;" href="@Url.Action("Create", "ReportUsers")" class="btn btn-block btn-primary">Add New</a></h3>
            <div class="box-tools" style="top: 10px;">
                <div class="input-group" style="width: 250px;">
                    <input type="text" name="table_search" id="searchText" class="form-control input-sm pull-right" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-sm btn-default" id="btnSearch"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div><!-- /.box-header -->
        <div id="searchList">
            @Html.Partial("_ReportUserList")
        </div>

    </div><!-- /.box -->
</section><!-- /.content -->

StockCharcha/Views/ReportUsers/_ReportUserList.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.ReportUserModel>
@using StockCharcha.Utils
@using StockCharcha.Utils.Enums

<script src="~/Content/admin/bootstrap/js/jquery.bootpag.js"></script>
<script src="~/Content/admin/scripts/Shared/Common.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        Common.Paging(@Model.NumberOfPages, @Model.CurrentPage, "ReportUsers");

        $(".drpActive").change(function () {
            $(".adminLoading").fadeIn("slow")
            var reportUserId = this.id;
            var isActive = this.value;

            $.ajax({
                url: '/ReportUsers/updateIsActive',
                data: JSON.stringify({ reportUserId: reportUserId,isActive:isActive }),
                type: 'POST',
                contentType: 'application/json',
                dataType: 'json',
                success: function (result) {
                    $(".adminLoading").fadeOut("slow");
                    alert(result);
                }
            });

        })
    });
</script>


<div class="box-body table-responsive no-padding">
    @if (Model.Data.Count() == 0 || Model == null)
    {
        int cnt = Model.Data.Count() + 1;
        <table class="table table-striped">
            <tr>
                <td colspan="@cnt">No Records Found.</td>
            </tr>
        </table>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>FromUser</th>
                    <th>ToUser</th>
                    <th>Comment</th>
                    <th>IsActive</th>
                </tr>
            </thead>
            <tbody id="itemContainer">
                @foreach (var item in Model.Data.OrderByDescending(x => x.CreatedOn))
                {
                    <tr>
                        <td>@item.FromUser</td>
                        <td>@item.ToUser</td>
                        <td>@item.Comments</td>
                        <td>
                            @Html.DropDownList("Status", new List<SelectListItem>
                             {
                                new SelectListItem{ Text="True", Value = "1", Selected= Convert.ToBoolean(item.IsActive)?true :false},
                                new SelectListItem{ Text="False", Value = "0", Selected= Convert.ToBoolean(!item.IsActive)?true :false }
                             }, new { @id = item.Id, @class = "drpActive" })
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <p class="paging"></p>
                    </td>
                </tr>
            </tfoot>
        </table>
    }

</div><!-- /.box-body -->