StockCharcha/Controllers/RegistrationMasterController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StockCharcha.DataAccess;
using StockCharcha.Models;
using System.Web.Security;
using System.IO;
using StockCharcha.Filters;
using StockCharcha.Utils;
using StockCharcha.Utils.Utilities;
using StockCharcha.Helpers;

namespace StockCharcha.Controllers
{
    public class RegistrationMasterController : Controller
    {
        private StockCharchaEntities db = new StockCharchaEntities();
        public const int PageSize = CommonConstants.PageSize;
        [SessionExistFilter]
        public ActionResult Index()
        {
            List<RegistrationModel> registrationList = new List<RegistrationModel>();
            var registration = new PagedData<RegistrationModel>();
            try
            {
                var registrationMasters = db.RegistrationMasters.Include(r => r.aspnet_Users).Where(x => x.IsDeleted == false).ToList();

                registrationList.AddRange(registrationMasters.Select(x => new RegistrationModel
                {
                    Id = x.Id,
                    UserName = x.aspnet_Users.UserName,
                    RoleId = GetRolesForUser(x.aspnet_Users.UserName),
                    Mobile = x.Mobile,
                    //CreatedByName = Convert.ToString(Membership.GetUser(x.CreatedBy).UserName),
                    Email = Convert.ToString(Membership.GetUser(x.aspnet_Users.UserName).Email),
                    IsDeleted = Convert.ToBoolean(x.IsDeleted)
                }));
                registration.Data = registrationList.Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                registration.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)registrationList.Count() / PageSize));
                registration.CurrentPage = 1;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(registration);
        }

        public ActionResult GetListByPage(string searchText, int page)
        {
            List<RegistrationModel> registrationList = new List<RegistrationModel>();
            var registration = new PagedData<RegistrationModel>();

            if (!string.IsNullOrEmpty(searchText))
            {
                registration = GetList(searchText, page);
                return PartialView("_RegistrationList", registration);
            }
            var registrationMasters = db.RegistrationMasters.Include(r => r.aspnet_Users).Where(x => x.IsDeleted == false).ToList();

            registrationList.AddRange(registrationMasters.Select(x => new RegistrationModel
            {
                Id = x.Id,
                UserName = x.aspnet_Users.UserName,
                RoleId = GetRolesForUser(x.aspnet_Users.UserName),
                Mobile = x.Mobile,
                //CreatedByName = Convert.ToString(Membership.GetUser(x.CreatedBy).UserName),
                Email = Convert.ToString(Membership.GetUser(x.aspnet_Users.UserName).Email),
                IsDeleted = Convert.ToBoolean(x.IsDeleted)
            }));
            registration.Data = registrationList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
            registration.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)registrationList.Count() / PageSize));
            registration.CurrentPage = page;

            return PartialView("_RegistrationList", registration);
        }

        public string GetRolesForUser(string userName)
        {
            try
            {
                string roleName = Roles.GetRolesForUser(userName)[0];
                return roleName;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return string.Empty;
        }
        public ActionResult Create()
        {
            try
            {
                ViewBag.RoleId = new SelectList(db.aspnet_Roles, "RoleId", "RoleName");
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(new RegistrationModel());
        }

        public ActionResult AddOrEditRegistration(RegistrationModel model, HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                    model.Photo = UploadImage(file);

                if (ModelState.IsValid)
                {
                    MembershipUser checkUser = Membership.GetUser(model.UserName);

                    if (model.Id == 0)
                    {
                        if (checkUser != null)
                        {
                            ModelState.AddModelError("checkUser", "User Name already exist.");
                            ViewBag.RoleId = new SelectList(db.aspnet_Roles, "RoleId", "RoleName", model.RoleId);
                            return View("Create", model);
                        }
                        else
                        {
                            string userName = Membership.GetUserNameByEmail(model.Email);
                            if (!string.IsNullOrEmpty(userName))
                            {
                                ModelState.AddModelError("checkEmail", "Email already exist.");
                                ViewBag.RoleId = new SelectList(db.aspnet_Roles, "RoleId", "RoleName", model.RoleId);
                                return View("Create", model);
                            }
                        }

                        Membership.CreateUser(model.UserName, model.Password, model.Email);
                        string roleName = db.aspnet_Roles.Where(x => x.RoleId == new Guid(model.RoleId)).FirstOrDefault().RoleName;
                        Roles.AddUserToRole(model.UserName, roleName);

                        RegistrationMaster registrationModel = new RegistrationMaster
                        {
                            UserId = new Guid(Membership.GetUser(model.UserName).ProviderUserKey.ToString()),
                            Mobile = model.Mobile,
                            Photo = model.Photo,
                            Description = model.Description,
                            UserTag = model.UserTag,
                            Website = model.Website,
                            CreatedBy = new Guid(Membership.GetUser(model.UserName).ProviderUserKey.ToString()),
                            CreatedOn = DateTime.Now,
                            IsDeleted = false
                        };

                        db.RegistrationMasters.Add(registrationModel);
                        db.SaveChanges();
                        TempData[CommonConstants.ModelStatus] = CommonConstants.ModelInsertStatus;
                        TempData[CommonConstants.MessageStatus] = CommonConstants.AddStatus;
                        SiteActivityErrorsUtil.SiteActivity("AddOrEditRegistration", registrationModel.Id.ToString(), "New registration");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        RegistrationMaster registrationModel = db.RegistrationMasters.Find(model.Id);

                        var user = from s in db.RegistrationMasters
                                   where s.UserId == (Guid)checkUser.ProviderUserKey && s.Id != model.Id
                                   select s;
                        if (user.Count() > 0)
                        {
                            ModelState.AddModelError("checkUser", "User Name already exist.");
                            ViewBag.RoleId = new SelectList(db.aspnet_Roles, "RoleId", "RoleName", model.RoleId);
                            return View("Create", model);
                        }
                        else
                        {
                            string userName = Membership.GetUserNameByEmail(model.Email);
                            MembershipUser checkUserEmail = Membership.GetUser(userName);
                            var userEmail = from s in db.aspnet_Membership
                                            where s.Email == model.Email && s.UserId != (Guid)checkUser.ProviderUserKey
                                            select s;

                            if (userEmail.Count() > 0)
                            {
                                ModelState.AddModelError("checkEmail", "Email already exist.");
                                ViewBag.RoleId = new SelectList(db.aspnet_Roles, "RoleId", "RoleName", model.RoleId);
                                return View("Create", model);
                            }
                        }

                        if (registrationModel != null)
                        {
                            registrationModel.UserId = new Guid(Membership.GetUser(model.UserName).ProviderUserKey.ToString());
                            registrationModel.Mobile = model.Mobile;
                            registrationModel.Photo = model.Photo != null ? model.Photo : registrationModel.Photo;
                            registrationModel.Description = model.Description;
                            registrationModel.UserTag = model.UserTag;
                            registrationModel.Website = model.Website;
                            registrationModel.IsDeleted = model.IsDeleted;
                            db.SaveChanges();
                        }
                        TempData[CommonConstants.ModelStatus] = CommonConstants.ModelUpdateStatus;
                        TempData[CommonConstants.MessageStatus] = CommonConstants.UpdateStatus;
                        SiteActivityErrorsUtil.SiteActivity("AddOrEditRegistration", registrationModel.Id.ToString(), "update registration");
                        return RedirectToAction("Index");

StockCharcha/Views/RegistrationMaster/Create.cshtml
@model StockCharcha.Models.RegistrationModel
@using StockCharcha.Utils
@{
    ViewBag.Title = Model.Id > 0 ? "Update" : "Create";
    string pageTitle = Model.Id > 0 ? "Update" : "Create";
}
<div class="notifications-align">
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInvalidStatus)
    {
        <div class="alert alert-danger show top-notification">
            <button class="close" data-dismiss="alert">x</button>
            @TempData[CommonConstants.MessageStatus]
        </div>
    }
</div>


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Registration</h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "RegistrationMaster")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","RegistrationMaster")">Registration</a></li>
        <li class="active">Create</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">@pageTitle</h3>
        </div><!-- /.box-header -->
        @using (Html.BeginForm("AddOrEditRegistration", "RegistrationMaster", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
        {
            <div class="box-body">

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.RoleId, "Role")
                            @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "form-control select2", @style = "width: 100%;" })
                            @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName)

                            @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            @Html.ValidationMessage("checkUser", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email)

                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            @Html.ValidationMessage("checkEmail", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Mobile)

                            @Html.TextBoxFor(model => model.Mobile, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>
                @if (Model.Id == 0)
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Password)

                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.ConfirmPassword)

                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })

                            </div>
                        </div>
                    </div>
                }
                else
                {
                    @Html.HiddenFor(m => m.Password, new { @class = "form-control" })
                    @Html.HiddenFor(m => m.ConfirmPassword, new { @class = "form-control" })
                }
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Website)

                            @Html.TextBoxFor(model => model.Website, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserTag)

                            @Html.TextBoxFor(model => model.UserTag, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserTag, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Photo)

                            <input type="file" name="file" id="file" />
                            @Html.ValidationMessage("NoFile")
                            @if (Model.Id != 0)
                            {
                                <img src="@Url.Action("showImage", "RegistrationMaster", new { id = Model.Id })" alt="Image" height="100" width="100" />
                            }

                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)

                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>


            </div><!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">@pageTitle</button>
            </div>
        }
    </div><!-- /.box -->


</section><!-- /.content -->
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(function () {
        //Initialize Select2 Elements
        $("#RoleId").select2();
    });
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockCharcha/Views/RegistrationMaster/Delete.cshtml
@model StockCharcha.DataAccess.RegistrationMaster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RegistrationMaster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

      
        <dt>
            @Html.DisplayNameFor(model => model.UserTag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aspnet_Users.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aspnet_Users.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
            @Html.ActionLink(
    "Delete",
    "RegistrationMaster",
    "Product",
    new { confirm = true, other_parameter = "some_more_parameter" },
    new { onclick = "return confirm('Do you really want to delete this product?')" })


        </div>
    }
</div>

StockCharcha/Views/RegistrationMaster/Details.cshtml
@model StockCharcha.DataAccess.RegistrationMaster

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RegistrationMaster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aspnet_Users.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aspnet_Users.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StockCharcha/Views/RegistrationMaster/Edit.cshtml
@model StockCharcha.DataAccess.RegistrationMaster

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrationMaster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserTag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserTag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserTag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockCharcha/Views/RegistrationMaster/Index.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.RegistrationModel>

@using StockCharcha.Utils

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/admin/css/adminLoading.css" rel="stylesheet" />
<script src="@Url.Content("~/Content/admin/scripts/jquery-1.8.2.min.js")"></script>
@*<script src="~/Scripts/bootstrap.min.js"></script>*@

<script type="text/javascript">
    $(window).load(function () {
        // Animate loader off screen
        $(".adminLoading").fadeOut("slow");
    });
    $(document).ready(function () {
        $("#btnSearch").click(function (evt) {
            $(".adminLoading").fadeIn("slow")
            $.ajax({
                url: '@Url.Action("GetListByPage")',
                data: JSON.stringify({ "searchText": $("#searchText").val(), "page": 1 }),
                type: 'POST',
                contentType: 'application/json',
                success: function (data) {
                    $("#searchList").html(data);
                },
                complete: function () {
                    $(".adminLoading").fadeOut("slow");
                }
            });
        });
    });
</script>



<div class="notifications-align">
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInsertStatus)
    {
    <div class="alert alert-success show top-notification">
        <button class="close" data-dismiss="alert">x</button>
        @TempData[CommonConstants.MessageStatus]
    </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelUpdateStatus)
    {
    <div class="alert alert-success show top-notification">
        <button class="close" data-dismiss="alert">x</button>
        @TempData[CommonConstants.MessageStatus]
    </div>
    }
    @if ((string)TempData[CommonConstants.ModelStatus] == CommonConstants.ModelInvalidStatus)
    {
    <div class="alert alert-danger show top-notification" style="padding: 8px;">
        <button class="close" data-dismiss="alert">x</button>
        @TempData[CommonConstants.MessageStatus]
    </div>
    }
</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Registration</h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","RegistrationMaster")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Index</li>
    </ol>
</section>

<!-- Main content -->
<div class="adminLoading"></div>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title"><a href="@Url.Action("Create","RegistrationMaster")" class="btn btn-block btn-primary">Add New</a></h3>
            <div class="box-tools" style="top: 10px;">
                <div class="input-group" style="width: 250px;">
                    <input type="text" name="table_search" id="searchText" class="form-control input-sm pull-right" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-sm btn-default" id="btnSearch"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div><!-- /.box-header -->
        <div id="searchList">
            @Html.Partial("_RegistrationList")
        </div>
    </div><!-- /.box -->
</section><!-- /.content -->

StockCharcha/Views/RegistrationMaster/_RegistrationList.cshtml
@model StockCharcha.Helpers.PagedData<StockCharcha.Models.RegistrationModel>
@using StockCharcha.Utils

<script src="~/Content/admin/bootstrap/js/jquery.bootpag.js"></script>
<script src="~/Content/admin/scripts/Shared/Common.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        Common.Paging(@Model.NumberOfPages, @Model.CurrentPage, "RegistrationMaster");
    });
</script>


<div class="box-body table-responsive no-padding">
    @if (Model.Data.Count() == 0 || Model == null)
    {
        int cnt = Model.Data.Count() + 1;
        <table class="table table-striped">
            <tr>
                <td colspan="@cnt">No Records Found.</td>
            </tr>
        </table>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Mobile</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="itemContainer">
                @foreach (var item in Model.Data.OrderByDescending(x => x.CreatedOn))
                {
                    <tr>
                        <td>@item.UserName</td>
                        <td>@item.Mobile</td>
                        <td>@item.Email</td>
                        <td>@item.RoleId</td>
                        <td>
                            <a href="@Url.Action("Edit", "RegistrationMaster", new { id = item.Id })">
                                <img src="~/Content/admin/images/edit.png" />
                            </a> &nbsp; &nbsp;
                            <a href="@Url.Action("Delete", "RegistrationMaster", new { confirm = true, id = item.Id, onclick = "return confirm('" + CommonConstants.ConfirmDelete + "')" })">
                                <img src="~/Content/admin/images/delete.png" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <p class="paging"></p>
                    </td>
                </tr>
            </tfoot>
        </table>
    }

</div><!-- /.box-body -->