StockCharcha/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using StockCharcha.DataAccess;
using StockCharcha.Filters;
using StockCharcha.Utils.Utilities;
using StockCharcha.Utils;
using StockCharcha.Helpers;

namespace StockCharcha.Controllers
{
    public class BlogsController : Controller
    {
        private StockCharchaEntities db = new StockCharchaEntities();
        public const int PageSize = CommonConstants.PageSize;
        // GET: Blogs
        [SessionExistFilter]
        public ActionResult Index()
        {
            List<Blog> blogList = new List<Blog>();
            var blog = new PagedData<Blog>();
            try
            {
                blogList = db.Blogs.Include(b => b.aspnet_Users).Include(b => b.aspnet_Users1).OrderByDescending(x => x.CreatedOn).ToList();
                blog.Data = blogList.Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                blog.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)blogList.Count() / PageSize));
                blog.CurrentPage = 1;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(blog);
        }

        public ActionResult GetListByPage(string searchText, int page)
        {
            List<Blog> blogList = new List<Blog>();
            var blog = new PagedData<Blog>();
            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    blog = GetList(searchText, page);
                    return PartialView("_BlogList", blog);
                }

                blogList = db.Blogs.Include(b => b.aspnet_Users).Include(b => b.aspnet_Users1).OrderByDescending(x => x.CreatedOn).ToList();
                blog.Data = blogList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                blog.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)blogList.Count() / PageSize));
                blog.CurrentPage = page;
                return PartialView("_BlogList", blog);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return PartialView("_BlogList", new PagedData<Blog>());
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        public PagedData<Blog> GetList(string searchText, int page)
        {
            try
            {
                List<Blog> blogList = new List<Blog>();
                var blog = new PagedData<Blog>();
                var blogs = db.Blogs.Where(x => x.Symbol.ToLower().Contains(searchText)).ToList();

                blogList.AddRange(blogs.Select(x => new Blog
                {
                    Id = x.Id,
                    Symbol = x.Symbol,
                    Everyone = x.Everyone,
                    OnlyFollowers = x.OnlyFollowers,
                    TrendInSights = x.TrendInSights,
                    EmailOnReply = x.EmailOnReply,
                    IsPublished = x.IsPublished,
                    CreatedOn = x.CreatedOn
                }));
                blog.Data = blogList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                blog.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)blogList.Count() / PageSize));
                blog.CurrentPage = page;
                return blog;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return new PagedData<Blog>();
        }
        public JsonResult updateIsPublish(long blogId)
        {
            try
            {
                Blog blog = db.Blogs.Find(blogId);
                blog.IsPublished = false;
                db.SaveChanges();
                SiteActivityErrorsUtil.SiteActivity("UpdateIsPublish", "", "Blog unpublished");
                return Json("Updated.");
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return Json("Something went wrong.");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockCharcha/Controllers/HelpController.cs
using StockCharcha.DataAccess;
using StockCharcha.Filters;
using StockCharcha.Helpers;
using StockCharcha.Models;
using StockCharcha.Utils;
using StockCharcha.Utils.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StockCharcha.Controllers
{
    public class HelpController : Controller
    {
        private StockCharchaEntities db = new StockCharchaEntities();
        public const int PageSize = CommonConstants.PageSize;
        // GET: Blogs
        [SessionExistFilter]
        public ActionResult Index()
        {
            List<HelpModel> helpList = new List<HelpModel>();
            var help = new PagedData<HelpModel>();
            try
            {
                var questionList = db.HelpQuestions.ToList();
                helpList.AddRange(questionList.Select(x => new HelpModel
                {
                    Id = x.Id,
                    FromUser = new Guid(x.FromUser.ToString()),
                    Question = x.Description,
                    CreatedOn = Convert.ToDateTime(x.CreatedOn),
                    IsResponded = Convert.ToBoolean(x.IsResponded),
                    IsActive = Convert.ToBoolean(x.IsActive)
                }));

                helpList = helpList.OrderByDescending(x => x.CreatedOn).ToList();
                help.Data = helpList.Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                help.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)helpList.Count() / PageSize));
                help.CurrentPage = 1;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(help);
        }

        public ActionResult GetListByPage(string searchText, int page)
        {
            List<HelpModel> helpList = new List<HelpModel>();
            var help = new PagedData<HelpModel>();
            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    help = GetList(searchText, page);
                    return PartialView("_HelpList", help);
                }

                var questionList = db.HelpQuestions.ToList();
                helpList.AddRange(questionList.Select(x => new HelpModel
                {
                    Id = x.Id,
                    FromUser = new Guid(x.FromUser.ToString()),
                    Question = x.Description,
                    CreatedOn = Convert.ToDateTime(x.CreatedOn),
                    IsResponded = Convert.ToBoolean(x.IsResponded),
                    IsActive = Convert.ToBoolean(x.IsActive)
                }));

                helpList = helpList.OrderByDescending(x => x.CreatedOn).ToList();
                help.Data = helpList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                help.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)helpList.Count() / PageSize));
                help.CurrentPage = page;
                return PartialView("_HelpList", help);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return PartialView("_HelpList", new PagedData<Blog>());
        }

        public PagedData<HelpModel> GetList(string searchText, int page)
        {
            try
            {
                List<HelpModel> helpList = new List<HelpModel>();
                var help = new PagedData<HelpModel>();

                var questionList = db.HelpQuestions.Where(x => x.Description.ToLower().Contains(searchText)).ToList();
                helpList.AddRange(questionList.Select(x => new HelpModel
                {
                    Id = x.Id,
                    FromUser = new Guid(x.FromUser.ToString()),
                    Question = x.Description,
                    CreatedOn = Convert.ToDateTime(x.CreatedOn),
                    IsResponded = Convert.ToBoolean(x.IsResponded),
                    IsActive = Convert.ToBoolean(x.IsActive)
                }));

                help.Data = helpList.Skip(PageSize * (page - 1)).Take(PageSize).OrderByDescending(x => x.CreatedOn).ToList();
                help.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)helpList.Count() / PageSize));
                help.CurrentPage = page;
                return help;
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return new PagedData<HelpModel>();
        }

        public ActionResult View(long id)
        {
            try
            {
                Guid userId = WebUtil.GetSessionValue<Guid>(CommonConstants.UserId); ;
                if (userId == Guid.Empty)
                {
                    return RedirectToAction("Index");
                }

                //answerList
                List<HelpAnswerModel> helpAnswerListModel = new List<HelpAnswerModel>();
                var helpAnswerList = db.HelpAnswers.Where(x => x.HelpQuestionId == id).ToList();

                if (helpAnswerList.Count() > 0)
                {
                    helpAnswerListModel.AddRange(helpAnswerList.Select(x => new HelpAnswerModel
                    {
                        Id = x.Id,
                        HelpQuestionId = id,
                        FromUser = new Guid(x.FromUser.ToString()),
                        Description = x.Description,
                        CreatedOn = Convert.ToDateTime(x.CreatedOn),
                        IsRead = Convert.ToBoolean(x.IsRead),
                        IsActive = Convert.ToBoolean(x.IsActive),
                        Username = Membership.GetUser(new Guid(x.FromUser.ToString())).UserName,
                        UserImage = GetUserImage(new Guid(x.FromUser.ToString()), CommonConstants.userImage32.ToString()),
                        LoggedInUserId = userId
                    }));
                }

                var que = db.HelpQuestions.Where(x => x.Id == id).FirstOrDefault();

                HelpModel helpModel = new HelpModel
                {
                    HelpAnswerModel = helpAnswerListModel,
                    UserQuestion = string.Format("{0} [{1}]", que.Description, Membership.GetUser(new Guid(que.FromUser.ToString())))
                };
                ViewBag.questionId = id;
                return View(helpModel);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return View(new HelpModel());
        }

        public ActionResult AnswerListByQuestion(long questionId)
        {
            try
            {
                Guid userId = WebUtil.GetSessionValue<Guid>(CommonConstants.UserId);
                if (userId == Guid.Empty)
                {
                    return RedirectToAction("Index");
                }

                //answerList
                List<HelpAnswerModel> helpAnswerListModel = new List<HelpAnswerModel>();
                var helpAnswerList = db.HelpAnswers.Where(x => x.FromUser == userId).ToList();

                if (helpAnswerList.Count() > 0)
                {
                    helpAnswerListModel.AddRange(helpAnswerList.Select(x => new HelpAnswerModel
                    {
                        Id = x.Id,
                        HelpQuestionId = questionId,
                        FromUser = new Guid(x.FromUser.ToString()),
                        Description = x.Description,
                        CreatedOn = Convert.ToDateTime(x.CreatedOn),
                        IsRead = Convert.ToBoolean(x.IsRead),
                        IsActive = Convert.ToBoolean(x.IsActive),
                        Username = Membership.GetUser(new Guid(x.FromUser.ToString())).UserName,
                        UserImage = GetUserImage(new Guid(x.FromUser.ToString()), CommonConstants.userImage32.ToString()),
                        LoggedInUserId = userId
                    }));
                }

                HelpModel helpModel = new HelpModel
                {
                    HelpAnswerModel = helpAnswerListModel
                };
                ViewBag.questionId = questionId;
                return PartialView("_HelpAnswerListByQuestion", helpModel);
            }
            catch (Exception e)
            {
                SiteActivityErrorsUtil.SiteError(e);
            }
            return PartialView("_HelpAnswerListByQuestion", new HelpModel());
        }

        public ActionResult SaveAnswer(long questionId, string answer)
        {
            try
            {
                Guid userId = WebUtil.GetSessionValue<Guid>(CommonConstants.UserId);
                if (userId == Guid.Empty)
                {
                    return RedirectToAction("Index");
                }

                //Save Answer
                HelpAnswer helpAnswer = new HelpAnswer
                {
                    HelpQuestionId = questionId,
                    FromUser = userId,
                    Description = answer,
                    CreatedOn = DateTime.Now,
                    IsRead = false,
                    IsActive = true
                };
                db.HelpAnswers.Add(helpAnswer);
                db.SaveChanges();

                //answerList
                List<HelpAnswerModel> helpAnswerListModel = new List<HelpAnswerModel>();
                var helpAnswerList = db.HelpAnswers.Where(x => x.HelpQuestionId == questionId).ToList();

                if (helpAnswerList.Count() > 0)
                {
                    helpAnswerListModel.AddRange(helpAnswerList.Select(x => new HelpAnswerModel
                    {
                        Id = x.Id,
                        FromUser = new Guid(x.FromUser.ToString()),
                        Description = x.Description,

StockCharcha/Views/Shared/_AlertMessage.cshtml
<script type="text/html" id="successTemplate">
    <div class="alert alert-success" style="text-align: center;">
        <button data-dismiss="alert" class="close">x</button>
        <span data-content="status"></span>
    </div>
</script>
<script type="text/html" id="errorTemplate">
    <div class="alert alert-error" style="text-align: center;">
        <button data-dismiss="alert" class="close">x</button>
        <span data-content="status"></span>
    </div>
</script>

StockCharcha/Views/Shared/_HomeLayout.cshtml
@using StockCharcha.Utils
@using StockCharcha.Utils.Utilities
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SC | @ViewBag.Title</title>
    @Styles.Render("~/Content/CommonBootstrapCss")
    @Styles.Render("~/Content/CommonCss")
    @Scripts.Render("~/bundles/CommonJs")
    <link href="~/Content/web/css/font-awesome.min.css" rel="stylesheet" />
    @*<script src="~/Content/web/bootstrap/js/bootstrap-select.js"></script>
    <link href="~/Content/web/bootstrap/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Menu/demo.css" rel="stylesheet" />
    <script src="~/Content/Menu/modernizr.custom.js"></script>*@

    <!--Notification-->
    <link href="~/Content/noty/animate.css" rel="stylesheet" />
    <script src="~/Content/noty/packaged/jquery.noty.packaged.js"></script>
    <script src="~/Content/noty/notification_html.js"></script>
    <!--Notification-->
</head>

<body>
    <div class="headerStrip">
        <div class="gridContainer clearfix">
            <div class="notifications" style="z-index: 999;position: fixed;top: 1px;left: 0px;width: 100%;"></div>
            <div id="LayoutDiv1">
                <div class="col-sm-3 padlftnn">
                    @if (WebUtil.GetSessionValue<Guid>(CommonConstants.UserIdWeb) != Guid.Empty)
                    {
                        <a href="@Url.RouteUrl("Dashboard")" class="headerLogo"><img src="~/Content/web/images/logo.png" alt="Stock Charcha" width="260" /></a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "Home")" class="headerLogo"><img src="~/Content/web/images/logo.png" alt="Stock Charcha" width="260" /></a>
                    }

                </div>
                <div class="col-sm-1 tabDispNon"> </div>
                <div class="col-sm-8 tab-col-9">
                    @RenderSection("RegisterAndLogin")
                    @RenderSection("HeaderShareIdea", false)
                    @RenderSection("Search")
                </div>
            </div>
        </div>
        @RenderSection("Menu")
    </div>

    @RenderBody()
    @RenderSection("HomeBody")
    @RenderSection("Footer", false)

    @Html.Partial("_AlertMessage")
</body>
</html>
<script src="~/Scripts/Web/Autocomplete/jquery-ui.js"></script>
@*<script src="~/Content/Menu/flexmenu.min.js"></script>*@
<script src="~/Content/Menu/flexmenu.js"></script>
<script>
    $('ul.menu.flex').flexMenu();
    $('ul.menu.flex-multi').flexMenu({
        showOnHover: false
    })
</script>

StockCharcha/Views/Shared/_Sidebar.cshtml
@using StockCharcha.Utils
@using StockCharcha.Utils.Utilities
@{
    var reportUrls = new string[] { "/RegistrationMaster", "/RegistrationMaster/AddOrEditRegistration", "/RegistrationMaster/Edit/", "/RegistrationMaster/Index", "/RegistrationMaster/Create",
                                    "/SymbolMasters", "/SymbolMasters/AddOrEditSymbol", "/SymbolMasters/Edit/", "/SymbolMasters/Index", "/SymbolMasters/Create",
                                    "/Blogs", "/Blogs/Index","/ReportUsers", "/ReportUsers/Index"};
    string menuClass = string.Empty;
    if (reportUrls.Any(x => (HttpContext.Current.Request.Url.AbsolutePath.Contains(x))))
    {
        menuClass = "active";
    }

    var logsUrls = new string[] { "/SiteActivity", "/SiteActivity/Index",
                                   "/SiteErrors", "/SiteErrors/Index"};

    string logsClass = string.Empty;
    if (logsUrls.Any(x => (HttpContext.Current.Request.Url.AbsolutePath.Contains(x))))
    {
        logsClass = "active";
    }

    var importUrls = new string[] { "/ImportSymbols", "/ImportSymbols/Index" };
    string importClass = string.Empty;
    if (importUrls.Any(x => (HttpContext.Current.Request.Url.AbsolutePath.Contains(x))))
    {
        importClass = "active";
    }

    var settingUrls = new string[] { "/Setting", "/Setting/Index",
                                     "/Setting/TemplateList", "/Setting/Template"};
    string settingClass = string.Empty;
    if (settingUrls.Any(x => (HttpContext.Current.Request.Url.AbsolutePath.Contains(x))))
    {
        settingClass = "active";
    }

    var helpUrls = new string[] { "/Help", "/Help/Index"};
    
    string helpClass = string.Empty;
    if (helpUrls.Any(x => (HttpContext.Current.Request.Url.AbsolutePath.Contains(x))))
    {
        helpClass = "active";
    }
    
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Content/admin/images/User_Avata.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                @{string userName = WebUtil.GetSessionValue<string>(CommonConstants.UserName).ToString();}
                <p>@userName</p>
                @*<a href="#"><i class="fa fa-circle text-success"></i> Online</a>*@
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">Menu</li>
            @*<li class="active treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active">
                            <a href="~/Content/admin/index.html">
                                <i class="fa fa-circle-o"></i>

                                Dashboard v1
                            </a>
                        </li>
                        <li>
                            <a href="~/Content/admin/index2.html">
                                <i class="fa fa-circle-o"></i> Dashboard

                                v2
                            </a>
                        </li>
                    </ul>
                </li>*@

            <li class="treeview @menuClass">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Masters</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/RegistrationMaster")
                 || HttpContext.Current.Request.Url.AbsolutePath.Contains("/RegistrationMaster/Edit/")
                                || HttpContext.Current.Request.Url.AbsolutePath.Equals("/RegistrationMaster/AddOrEditRegistration")
                              || HttpContext.Current.Request.Url.AbsolutePath.Contains("/RegistrationMaster/Index")
                           || HttpContext.Current.Request.Url.AbsolutePath.Contains("/RegistrationMaster/Create") ? "active" : "")">
                        <a href="@Url.Action("Index", "RegistrationMaster")">
                            <i class="fa fa-circle-o"></i> Users
                        </a>
                    </li>

                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/SymbolMasters")
              || HttpContext.Current.Request.Url.AbsolutePath.Contains("/SymbolMasters/Edit/")
                          || HttpContext.Current.Request.Url.AbsolutePath.Equals("/SymbolMasters/AddOrEditSymbol")
                           || HttpContext.Current.Request.Url.AbsolutePath.Contains("/SymbolMasters/Index")
                        || HttpContext.Current.Request.Url.AbsolutePath.Contains("/SymbolMasters/Create") ? "active" : "")">
                        <a href="@Url.Action("Index","SymbolMasters")">
                            <i class="fa fa-circle-o"></i> Symbol
                        </a>
                    </li>
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/Blogs")
                              || HttpContext.Current.Request.Url.AbsolutePath.Contains("/Blogs/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "Blogs")">
                            <i class="fa fa-circle-o"></i> Blogs
                        </a>
                    </li>
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/ReportUsers")
                           || HttpContext.Current.Request.Url.AbsolutePath.Contains("/ReportUsers/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "ReportUsers")">
                            <i class="fa fa-user-times"></i> Report User
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview @logsClass">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Logs</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/SiteActivity")
                           || HttpContext.Current.Request.Url.AbsolutePath.Contains("/SiteActivity/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "SiteActivity")">
                            <i class="fa fa-circle-o"></i> Logs
                        </a>
                    </li>
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/SiteErrors")
                        || HttpContext.Current.Request.Url.AbsolutePath.Contains("/SiteErrors/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "SiteErrors")">
                            <i class="fa fa-circle-o"></i> Site Errors
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview @importClass">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Import</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/ImportSymbols")
                        || HttpContext.Current.Request.Url.AbsolutePath.Contains("/ImportSymbols/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "ImportSymbols")">
                            <i class="fa fa-circle-o"></i> Import Symbols
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview @settingClass">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Settings</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/Setting")
                     || HttpContext.Current.Request.Url.AbsolutePath.Contains("/Setting/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "Setting")">
                            <i class="fa fa-circle-o"></i> Settings
                        </a>
                    </li>
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/Setting/TemplateList")
                     || HttpContext.Current.Request.Url.AbsolutePath.Contains("/Setting/Template") ? "active" : "")">
                        <a href="@Url.Action("TemplateList", "Setting")">
                            <i class="fa fa-circle-o"></i> Template
                        </a>
                    </li>
                </ul>
            </li>



            <li class="treeview @helpClass">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Help</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.Equals("/Help") || 
                    HttpContext.Current.Request.Url.AbsolutePath.Contains("/Help/Index") ? "active" : "")">
                        <a href="@Url.Action("Index", "Help")">
                            <i class="fa fa-circle-o"></i> Help
                        </a>
                    </li>
                </ul>
            </li>


        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

StockCharcha/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/web/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/web/css/style.css" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <div class="content">
            <div class="col-sm-4">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="~/Content/web/images/logo.png" />
                    </a>
                </div>
            </div>
            @RenderSection("RegisterAndLogin")
        </div>
    </div>
    <div>
        @RenderBody()
        @RenderSection("HomeBody")
    </div>
</body>
</html>